import All from '../assets/icons/All';
import Computer from '../assets/icons/Computer';
import Printer from '../assets/icons/Printer';
import Signage from '../assets/icons/Signage';
import Solar from '../assets/icons/Solar';
import { help, cart } from './icons';
import { heroImg, lenovo, alienware, hpEvo, solarPanel, hpTransform, printer as printerImg, printer2, solarPanel2, multiPrinter } from './images';

export const menuLinks = [
    {
        id: 1,
        url: '',
        iconUrl: help,
        title: 'Help',
        hasDropDown: true,
        isCart: false,
        dropdown: {
          title : "Contact us",
          value : '08167677321',
        }
    },
    {
        id: 2,
        url: '/cart',
        iconUrl: cart,
        title: 'Cart',
        hasDropDown: false,
        isCart: true,
    },
]

export const heroCarousel = [
  {
    id: 1,
    url: '',
    heroImg: heroImg,
    title: 'Dell Vostro',
    desc: 'Always-ready 14-inch laptop that connects you to your world. Ideal combination of portability and productivity. They include AMD Ryzen™ 5000 series processors.',
    cta: 'Buy',
    slug: 'dell-vostro',
  },
  {
    id: 2,
    url: '',
    heroImg: lenovo,
    title: 'Lenovo YG',
    desc: 'Discover the Lenovo Yoga, a versatile 14-inch laptop designed to keep you connected and productive wherever you go.',
    cta: 'Buy',
    slug: 'lenovo-yoga',
  },
  {
    id: 3,
    url: '',
    heroImg: alienware,
    title: 'Alienware',
    desc: 'Always-ready 14-inch laptop that connects you to your world. Ideal combination of portability and productivity. They include AMD Ryzen™ 5000 series processors.',
    cta: 'Buy',
    slug: 'alienware',
  },
];

export const productTabs = [
  {
    id: 1,
    icon: <All />,
    title: 'All',
    category: 'all',
  },
  {
    id: 2,
    icon: <Computer />,
    title: 'Computers',
    category: 'computers',
  },
  {
    id: 3,
    icon: <Printer />,
    title: 'Printers',
    category: 'printers',
  },
  {
    id: 4,
    icon: <Solar />,
    title: 'Solar Panels',
    category: 'solar-panels',
  },
  {
    id: 5,
    icon: <Signage />,
    title: 'Digital Signage',
    category: 'signage',
  },
];

export const products = [
  {
    id: 1,
    title: 'Dell Vostro',
    unitsSold: 50,
    isNew: true,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: heroImg,
    desc: "<ul><li>Ultra slim with unmatched performance</li><li>256GB SSD provides room to store all your important files</li><li>Windows 11</li><li>Long lasting battery</li></ul>",
    category: 'computers',
    quantity: 50,
    isLiked: false,
    slug: 'dell-vostro',
    rating: 3,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 2,
    title: 'Multifunctional Printer',
    unitsSold: 50,
    isNew: false,
    price: 1500.00,
    isDiscount: true,
    discountPrice: 1050.00,
    sourceUrl: printerImg,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'printers',
    quantity: 50,
    isLiked: false,
    slug: 'multi-printer',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 3,
    title: 'HP evo Intel',
    unitsSold: 50,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: hpEvo,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 50,
    isLiked: true,
    slug: 'hp-evo',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 4,
    title: 'Panel solar s547',
    unitsSold: 250,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: solarPanel,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'solar-panels',
    quantity: 50,
    isLiked: false,
    slug: 'solar-s547',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 5,
    title: 'Panel solar PRO',
    unitsSold: 250,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: solarPanel2,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'solar-panels',
    quantity: 50,
    isLiked: true,
    slug: 'solar-pro',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 6,
    title: 'Impresora Multifuncional HP',
    unitsSold: 250,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: printer2,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'printers',
    quantity: 50,
    isLiked: false,
    slug: 'impresora-hp',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 7,
    title: 'HP Transform',
    unitsSold: 50,
    isNew: false,
    price: 1500.00,
    isDiscount: true,
    discountPrice: 1125.00,
    sourceUrl: hpTransform,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 20,
    isLiked: false,
    slug: 'hp-transform',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 8,
    title: 'Alienware X15',
    unitsSold: 50,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: alienware,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 20,
    isLiked: false,
    slug: 'alienware',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 9,
    title: 'Lenovo Yoga',
    unitsSold: 50,
    isNew: false,
    price: 999.00,
    isDiscount: false,
    discountPrice: 999.00,
    sourceUrl: lenovo,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 20,
    isLiked: true,
    slug: 'lenovo-yoga',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 10,
    title: 'Signage Multifuncional HP',
    unitsSold: 200,
    isNew: false,
    price: 999.00,
    isDiscount: true,
    discountPrice: 899.00,
    sourceUrl: printer2,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'signage',
    quantity: 1,
    isLiked: false,
    slug: 'signage-multi',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 11,
    title: 'HP Transform',
    unitsSold: 50,
    isNew: false,
    price: 1500.00,
    isDiscount: true,
    discountPrice: 1125.00,
    sourceUrl: hpTransform,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 20,
    isLiked: false,
    slug: 'hp-transform',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
  {
    id: 12,
    title: 'HP Transform',
    unitsSold: 50,
    isNew: false,
    price: 1500.00,
    isDiscount: true,
    discountPrice: 1125.00,
    sourceUrl: hpTransform,
    desc: 'This product is very functional and good. It provides the best value ever',
    category: 'computers',
    quantity: 20,
    isLiked: false,
    slug: 'hp-transform',
    rating: 4,
    details: {
      brand: 'HP',
      productCode: 1231234,
      colour: 'biege',
    }
  },
]